### ISSUE TITLE
[FEATURE ADDED] - ISSUE TEMPLATE 

### ISSUE THREAD

**Issue by prathamesh-borse** [Suraj-1411/WhatsApp#6]
Hey, @Suraj-1411 I noticed that this repository doesn't have any issue template for beginners.
Because of the issue template, it will become easy for project contributors to specify on which issue 
they want to work on it and give a description of it.

What do you think let me know below 👇

**Comment by Suraj-1411** [comment]
Thanks bro @prathamesh-borse I don't know what you did but thanks :)
